name: bearth_timer
description: "Customizable breath-hold timer for freediving & breathwork."
publish_to: 'none'
version: 0.9.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  wakelock_plus: ^1.2.1
  supabase_flutter: ^2.9.1
  crypto: ^3.0.3
  file_picker: ^10.1.9
  flutter_soloud: ^3.2.1
  path_provider: ^2.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#ffffff"
    theme_color: "#2196F3"

  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/icon.png"

  linux:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/sounds/clap1.wav
    - assets/sounds/clap2.wav
    - assets/sounds/clap3.wav
